name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Pack
      run: dotnet pack --no-build --configuration Release Garbacik.NetCore.EFCore.Extensions/Garbacik.NetCore.EFCore.Extensions.csproj --output .
    - name: Push Github Packages
      run: dotnet nuget push *.nupkg --no-symbols --skip-duplicate --source https://nuget.pkg.github.com/pawel90g/ --api-key ${{ secrets.PACKAGES_TOKEN }}
    - name: Push NuGet
      run: dotnet nuget push *.nupkg --no-symbols --skip-duplicate --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_ORG_API_KEY }}

